-- Users table
CREATE TABLE IF NOT EXISTS Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,
  role ENUM('passenger', 'driver', 'conductor', 'sacco_admin', 'system_admin') NOT NULL,
  avatar VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  approved BOOLEAN DEFAULT false,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Matatus table
CREATE TABLE IF NOT EXISTS Matatus (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sacco VARCHAR(255) NOT NULL,
  identifier VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  type ENUM('Regular', 'Long Distance', 'Express') NOT NULL DEFAULT 'Regular',
  route VARCHAR(255),
  capacity INT DEFAULT 14,
  featured BOOLEAN DEFAULT false,
  qrCode TEXT,
  status ENUM('Active', 'Under Maintenance', 'Out of Service') DEFAULT 'Active',
  amenities JSON DEFAULT '{}',
  departureSchedule JSON DEFAULT '{}',
  price DECIMAL(10, 2),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Trips table
CREATE TABLE IF NOT EXISTS Trips (
  id INT PRIMARY KEY AUTO_INCREMENT,
  origin VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  departureTime DATETIME NOT NULL,
  arrivalTime DATETIME,
  fare DECIMAL(10, 2) NOT NULL,
  driverId INT,
  matatuId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (driverId) REFERENCES Users(id) ON DELETE SET NULL,
  FOREIGN KEY (matatuId) REFERENCES Matatus(id) ON DELETE SET NULL
);

-- SaccoAdmins table
CREATE TABLE IF NOT EXISTS SaccoAdmins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  saccoName VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  routes TEXT DEFAULT '[]',
  approved BOOLEAN DEFAULT true,
  avatar VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Routes table
CREATE TABLE IF NOT EXISTS Routes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  active BOOLEAN DEFAULT true,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Admins table
CREATE TABLE IF NOT EXISTS Admins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Drivers table
CREATE TABLE IF NOT EXISTS Drivers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  licenseNumber VARCHAR(255) NOT NULL,
  sacco VARCHAR(255) NOT NULL,
  busIdentifier VARCHAR(255) NOT NULL,
  busType VARCHAR(255) DEFAULT 'Matatu',
  avatar VARCHAR(255),
  busPic VARCHAR(255),
  licenseDoc VARCHAR(255),
  approved BOOLEAN DEFAULT true,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Passengers table
CREATE TABLE IF NOT EXISTS Passengers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  approved BOOLEAN DEFAULT true,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Bookings table
CREATE TABLE IF NOT EXISTS Bookings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  passengerId INT,
  tripId INT,
  route VARCHAR(255),
  date VARCHAR(255),
  time VARCHAR(255),
  seats JSON,
  totalPrice DECIMAL(10, 2),
  passengers JSON,
  paymentMethod VARCHAR(255),
  sacco VARCHAR(255),
  tripType VARCHAR(255),
  seatsBooked INT DEFAULT 1,
  paid BOOLEAN DEFAULT false,
  status VARCHAR(255) DEFAULT 'pending',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (passengerId) REFERENCES Users(id) ON DELETE SET NULL,
  FOREIGN KEY (tripId) REFERENCES Trips(id) ON DELETE SET NULL
);
